src/controller/AppLauncher.java, src/controller/WelcomeController.java, src/view/welcome.fxml
created controller for welcome screen + modified AppLauncher and welcome view to work with controller
=> Controller Stuff

src/controller/AppLauncher.java
=> -Window size and title

src/controller/AppLauncher.java, src/controller/MainAppController.java, src/controller/WelcomeController.java, src/model/Model.java, src/view/app.fxml, src/view/welcome.fxml
Also added skeleton for app.fxml
*NOTE: NO LOGOUT OR EXIT FUNCTIONALITY YET
=> Now, valid login will call mainpage. EDIT: Now it simulates login and logout

src/controller/WelcomeController.java, src/model/Model.java, src/view/welcome.fxml
Make sure it works on your device, comment 👍 (`:+1`) if it works
@taylor1355 @juanduquevan you've been drafted as the testers 😀
=> Registration

src/model/AuthLevel.java
I made the enum for Authorization Level
=> AuthLevel Enum

src/main/java/controller/MainAppController.java
=> I have fixed some strange import in Karel's changes that prevent compile

2340_Project.iml, src/main/java/model/IUser.java, src/main/java/model/User.java
also i'm not sure if i should have added the .iml file, but git was bugging me about it being untracked
=> Delete IUser interface

.idea/modules/project_ifrit_main.iml, .idea/modules/project_ifrit_test.iml, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/controller/MainAppController.java, src/main/resources/fxml/app.fxml
-I changed all the gradle stuff because when I first tried to get the project to work with gmapsfx it ran fine with gradle but Intellij showed a bunch of errors because it didn't know what was going on
Unresolved Issue:
-there's some weird stuff going on with how GoogleMap event handlers are handled. Its like the default functionality (like popping up with option to refresh map on right click) overrides any functionality the client tries to add.
Stuff I Did:
-added a google map window to the home tab (I decided to stick with tabs now that we know gmapsfx works with the drag and drop fxml thing)
-added gmapsfx to gradle build file
-changed source directory of gradle build file so that running via gradle or application works (and more importantly the ide doesn't show errors when it compiles …
=> Initial Map Stuff + Making Gradle and Intellij friends

src/main/java/controller/MainAppController.java, src/main/resources/fxml/app.fxml
Also, the user can search for specific locations.
=> Now, the markers will show who has submitted the report and when.

src/main/java/controller/MainAppController.java, src/main/java/model/AccountType.java, src/main/java/model/Location.java, src/main/java/model/Model.java, src/main/java/model/QualityReport.java, src/main/java/model/WaterSourceReport.java
-Added QualityReport class
-Added creator methods in Model
-Changed text for report preview
-getSubmitterUsername() changed to getSubmitter() and returns User object (not Username)
=> Quality report

src/main/java/controller/MainAppController.java, src/main/resources/fxml/app.fxml
=> Refresh map

.gitignore, src/main/java/controller/MainAppController.java, src/main/java/controller/WelcomeController.java, src/main/resources/fxml/app.fxml, src/main/resources/fxml/welcome.fxml
-added enter binding to all of the various submit/confirm buttons
-added serialization (*.ser) files to .gitignore
=> Enter binding

src/main/java/controller/MainAppController.java, src/main/java/model/User.java, src/main/resources/fxml/WaterQualityEditor.fxml, src/main/resources/fxml/WaterSourceEditor.fxml, src/main/resources/fxml/app.fxml
Now created two new tabs
Note that these two fxml files still have to be connected to controller somehow.
=> Now, the list of quality reports and source reports are viewable

src/main/java/controller/AppLauncher.java, src/main/java/controller/Controller.java, src/main/java/controller/ControllerUtils.java, src/main/java/controller/EditUserController.java, src/main/java/controller/MainAppController.java, src/main/java/controller/QualityReportController.java, src/main/java/controller/SourceReportController.java, src/main/java/controller/WelcomeController.java, src/main/java/model/AccountType.java, src/main/java/model/Model.java, src/main/resources/fxml/app.fxml, src/main/resources/fxml/editUser.fxml, src/main/resources/fxml/qualityReport.fxml, src/main/resources/fxml/sourceReport.fxml
=> Separate windows

src/main/java/controller/MainAppController.java, src/main/java/controller/QGraphController.java, src/main/resources/fxml/GraphView.fxml
Still need to figure out how to populate graph.
=> Now, the history graph pops up in the dialog after clicking the marker

.idea/modules/project_ifrit_main.iml, .idea/modules/project_ifrit_test.iml, build.gradle, src/main/java/controller/MainAppController.java, src/main/java/model/Model.java, src/main/java/model/QualityReport.java, src/main/java/model/Report.java, src/main/java/model/WaterSourceReport.java
-Reports can now be 'hidden'
-Reports are hidden when a new report (of the same type) is created within 1 mile of another
-Reports still exist so history can be viewed
=> Hidden pins

src/main/java/controller/MainAppController.java, src/main/java/controller/QualityReportController.java, src/main/java/controller/SourceReportController.java, src/main/java/model/Location.java, src/main/java/model/Model.java
-now reports are hidden when a new report is added
-moved most of report hiding functionality to model
-cleaned up a couple of things
=> finished up report hiding functionality

src/main/java/model/Model.java, src/main/java/testing/TaylorTest.java
-added junit tests for modifyUsername in Model
-also modified model to allow test classes to get an empty model object
=> test stuff

src/test/java/model/KarelTest.java
Junit test for createQualityReport
=> Junit test for createQualityReport

src/test/java/model/StanTest.java
Could you look at my hideNearSourceReport test?
I think there might be something wrong with it.
=> My Tests for WaterSources method

.idea/modules/project_ifrit_test.iml, src/main/java/controller/MainAppController.java, src/main/java/controller/SourceReportController.java
Right click on the map to add a source report. 
To do: map and report history need to refresh automatically in order for new report to show up.
=> Right click to add report
